name: 💡 Feature Request
description: Propose a new feature for the platform
labels: [needs-triage, feature-request]
body:
- type: textarea
  attributes:
    label: Description
    description: Describe the feature
- type: textarea
  attributes:
    label: Requested By
    description: A bullet point list of the leads/customers that have requested this feature.
    value: |
      - Customer name and/or link to HubSpot contact
- type: markdown
  attributes:
    value: |
      Hint: Please remember to provide an effort estimate, if possible, as outlined in our handbook.
