name: Add new issues to the Relevant Boards

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  add-to-project-board:
    name: Add issue to project
    if: | 
      github.repository != 'FlowFuse/website' &&
      github.repository != 'FlowFuse/node-red-dashboard'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
         with:
           project-url: https://github.com/orgs/FlowFuse/projects/3
           github-token: ${{ secrets.token }}

  add-to-artwork-board:
    name: Add art requests to the Artwork board
    runs-on: ubuntu-latest
    steps:
       - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
         with:
           labeled: design, artwork
           label-operator: AND
           project-url: https://github.com/orgs/FlowFuse/projects/10
           github-token: ${{ secrets.token }}
  
  add-to-dashboard-backlog:
    name: Add issues to the Dashboard Backlog project board
    if: github.repository == 'FlowFuse/node-red-dashboard'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
          with:
            labeled: needs-triage
            project-url: https://github.com/orgs/FlowFuse/projects/15
            github-token: ${{ secrets.token }}
