name: Add new issues to the Relevant Boards

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  add-to-project-board:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
       - uses: actions/add-to-project@main
         with:
           project-url: https://github.com/orgs/flowforge/projects/3
           github-token: ${{ secrets.token }}

  add-to-artwork-board:
    name: Add art requests to the Artwork board
    runs-on: ubuntu-latest
    steps:
       - uses: actions/add-to-project@main
         with:
           labeled: design, artwork
           label-operator: AND
           project-url: https://github.com/orgs/flowforge/projects/3
           github-token: ${{ secrets.token }}
