name: Add new issues to the Product Board

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
       - uses: actions/add-to-project@main
         with:
           project-url: https://github.com/orgs/flowforge/projects/3
           github-token: ${{ secrets.token }}
